{% set name = "aiomqtt" %}
{% set version = "0.17.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 015e4a7fdd1f3f22ee5b70b8fc0e3cf8fa0b283618e813d222eeaed87974bfaa

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - paho-mqtt >=1.3.0
    - python

test:
  imports:
    - aiomqtt
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mossblaser/aiomqtt
  summary: An AsyncIO asynchronous wrapper around paho-mqtt.
  license: EPL-1.0
  license_file: EPLv1.txt

extra:
  recipe-maintainers:
    - nerohmot
