{% set name = "aiomqtt" %}
{% set version = "2.4.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ab0f18fc5b7ffaa57451c407417d674db837b00a9c7d953cccd02be64f046c17

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python 3.8
    - hatchling
    - pip
  run:
    - python >=3.8
    - paho-mqtt >=2.1.0,<3.0.0
    - typing_extensions >=4.4.0,<5.0.0

test:
  imports:
    - aiomqtt
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/empicano/aiomqtt
  summary: The idiomatic asyncio MQTT client
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - nerohmot
