{% set name = "aiomqtt" %}
{% set version = "0.1.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d4209813d5bfd0f0cadb1b5e85eb10c7636c453270f30863134fbfadcf9c3f43

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - paho-mqtt >=1.3.0
    - python

test:
  imports:
    - aiomqtt
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mossblaser/aiomqtt
  summary: An AsyncIO asynchronous wrapper around paho-mqtt.
  license: EPL-1.0
  license_file: EPLv1.txt

extra:
  recipe-maintainers:
    - nerohmot
