{% set name = "aiomqtt" %}
{% set version = "1.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8a41cbda3f5dcbedb8ad8568237693afbfda5b65b63b92ca85d7fa4f143f9b0a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - paho-mqtt >=1.3.0
    - python

test:
  imports:
    - aiomqtt
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mossblaser/aiomqtt
  summary: An AsyncIO asynchronous wrapper around paho-mqtt.
  license: EPL-1.0
  license_file: EPLv1.txt

extra:
  recipe-maintainers:
    - nerohmot
