schema_version: 1

context:
  name: aiomqtt
  version: "1.2.1"

package:
  name: ${{ name }}
  version: ${{ version }}
  
source:
  url: https://pypi.org/packages/source/a/aiomqtt/aiomqtt-${{ version }}.tar.gz
  sha256: 7582f4341f08ef7110dd9ab3a559454dc28ccda1eac502ff8f08a73b238ecede

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - poetry-dynamic-versioning
    - python ${{ python_min }}.*
  run:
    - paho-mqtt >=1.6.0,<2.0.0
    - python >=${{ python_min }}
    - typing_extensions >=4.4.0,<5.0.0

tests:
  - package_contents:
      strict: true
      files:
        - site-packages/aiomqtt/__init__.py
        - site-packages/aiomqtt/client.py
        - site-packages/aiomqtt/error.py
        - site-packages/aiomqtt/py.typed
        - site-packages/aiomqtt/types.py
        - site-packages/aiomqtt-${{ version }}.dist-info/INSTALLER
        - site-packages/aiomqtt-${{ version }}.dist-info/METADATA
        - site-packages/aiomqtt-${{ version }}.dist-info/RECORD
        - site-packages/aiomqtt-${{ version }}.dist-info/REQUESTED
        - site-packages/aiomqtt-${{ version }}.dist-info/WHEEL
        - site-packages/aiomqtt-${{ version }}.dist-info/direct_url.json
        - site-packages/aiomqtt-${{ version }}.dist-info/licenses/LICENSE
        # Tests artifacts
        - etc/conda/test-files/aiomqtt/*
  - python:
      imports:
        - aiomqtt
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"
  - script:
      - pytest --strict-config --strict-markers tests
    files:
      source:
        - tests/
        - pyproject.toml
    requirements:
      run:
        - anyio >=3.6.2,<4.0.0
        - furo >=2023.3.27,<2024.0.0
        - myst-parser >=1.0.0,<2.0.0
        - pytest >=7.3.1,<8.0.0

about:
  homepage: https://github.com/empicano/aiomqtt
  summary: The idiomatic asyncio MQTT client
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - nerohmot
    - MementoRC
    
